Number.isNumber=function(a){return"number"==typeof a};Number.compare=function(a,b){return a-b};Number.prototype.round=function(a){if(null==a)return Math.round(this);a=Math.pow(10,a);return Math.round(this*a)/a};String.ZeroWidthChar=String.fromCharCode(8203);String.SpacerChar="&#160;";String.isString=function(a){return"string"==typeof a};String.htmlText=function(a){return null==a||0==a.length?String.ZeroWidthChar:a};String.padLeft=function(a,b,c){a=String(a);for(c=c||" ";a.length<b;)a=c+a;return a};
String.padRight=function(a,b,c){a=String(a);for(c=c||" ";a.length<b;)a+=c;return a};String.repeat=function(a,b,c){c="";for(var d=0;d<b;d++)c+=a;return c};String.prototype.startsWith=function(a){var b=this.length;return null==a||b<a.length?!1:this.substr(0,a.length)==a};String.prototype.endsWith=function(a){var b=this.length;return null==a||b<a.length?!1:this.substr(b-a.length,a.length)==a};
Array.prototype.pushIf=function(){for(var a=0,b=arguments.length;a<b;a++){var c=arguments[a];-1==this.indexOf(c)&&this.push(c)}return this};Array.prototype.insert=function(a,b){a=Array.isArray(a)?a:[a];var c=[null!=b?b:this.length,0].concat(a);this.splice.apply(this,c);return this};Array.prototype.add=function(a){return this.insert(a,null)};
Array.prototype.remove=function(){for(var a=[],b=0,c=arguments.length;b<c;b++){var d=arguments[b],e=this.indexOf(d);-1!=this.indexOf(d)&&(a.push(d),this.splice(e,1))}return a};Array.prototype.removeAll=function(a){if(null==a)return[];a=Array.isArray(a)?a:[a];return this.remove.apply(this,a)};Array.prototype.removeAt=function(a){return this.splice(a,1)};Array.prototype.first=function(){return 0<this.length?this[0]:null};Array.prototype.last=function(){var a=this.length;return 0<a?this[a-1]:null};
Date.Milli="ms";Date.Second="s";Date.Minute="mi";Date.Hour="h";Date.Day="d";Date.Month="mo";Date.Year="y";Date.DaysInMonth=[31,28,31,30,31,30,31,31,30,31,30,31];Date.MillisPerDay=864E5;Date.MillisPerWeek=7*Date.MillisPerDay;Date.MonthNames="\u042f\u043d\u0432\u0430\u0440\u044c \u0424\u0435\u0432\u0440\u0430\u043b\u044c \u041c\u0430\u0440\u0442 \u0410\u043f\u0440\u0435\u043b\u044c \u041c\u0430\u0439 \u0418\u044e\u043d\u044c \u0418\u044e\u043b\u044c \u0410\u0432\u0433\u0443\u0441\u0442 \u0421\u0435\u043d\u0442\u044f\u0431\u0440\u044c \u041e\u043a\u0442\u044f\u0431\u0440\u044c \u041d\u043e\u044f\u0431\u0440\u044c \u0414\u0435\u043a\u0430\u0431\u0440\u044c".split(" ");
Date.MonthShortNames="\u042f\u043d\u0432 \u0424\u0435\u0432 \u041c\u0430\u0440 \u0410\u043f\u0440 \u041c\u0430\u0439 \u0418\u044e\u043d \u0418\u044e\u043b \u0410\u0432\u0433 \u0421\u0435\u043d \u041e\u043a\u0442 \u041d\u043e\u044f \u0414\u0435\u043a".split(" ");Date.DayNames="\u041f\u043e\u043d\u0435\u0434\u0435\u043b\u044c\u043d\u0438\u043a \u0412\u0442\u043e\u0440\u043d\u0438\u043a \u0421\u0440\u0435\u0434\u0430 \u0427\u0435\u0442\u0432\u0435\u0440\u0433 \u041f\u044f\u0442\u043d\u0438\u0446\u0430 \u0421\u0443\u0431\u0431\u043e\u0442\u0430 \u0412\u043e\u0441\u043a\u0440\u0435\u0441\u0435\u043d\u044c\u0435".split(" ");
Date.DayShortNames="\u041f\u043d \u0412\u0442 \u0421\u0440 \u0427\u0442 \u041f\u0442 \u0421\u0431 \u0412\u0441".split(" ");Date.isDate=function(a){return"[object Date]"===toString.call(a)};Date.isEqual=function(a,b){return a&&b?a.getTime()==b.getTime():!1};Date.isEqualMonth=function(a,b){return a&&b?a.getYear()==b.getYear()&&a.getMonth()==b.getMonth():!1};Date.isEqualDate=function(a,b){return a&&b?a.getYear()==b.getYear()&&a.getMonth()==b.getMonth()&&a.getDate()==b.getDate():!1};
Date.prototype.getMonthName=function(){return Date.MonthNames[this.getMonth()]};Date.prototype.getMonthShortName=function(){return Date.MonthShortNames[this.getMonth()]};Date.prototype.getDayName=function(){return Date.dayNames[this.getDayOfWeek()]};Date.prototype.getDayShortName=function(){return Date.dayShortNames[this.getDayOfWeek()]};Date.prototype.getDayOfWeek=function(){var a=this.getDay();return 0!=a?a-1:6};
Date.prototype.getFirstDateOfWeek=function(){var a=this.getDayOfWeek();return(new Date(this)).add(-a,Date.Day)};Date.prototype.getWeekOfYear=function(){var a=Date.UTC(this.getFullYear(),this.getMonth(),this.getDate()+3)/Date.MillisPerDay,a=Math.floor(a/7),b=(new nativeDate(a*Date.MillisPerWeek)).getUTCFullYear();return a-Math.floor(Date.UTC(b,0,7)/Date.MillisPerWeek)+1};Date.prototype.isLeapYear=function(){var a=this.getFullYear();return!(0!==(a&3)||!(a%100||0===a%400&&a))};
Date.prototype.getFirstDayOfMonth=function(){var a=(this.getDay()-(this.getDate()-1))%7,a=0>a?a+7:a;return 0!=a?a-1:6};Date.prototype.getLastDayOfMonth=function(){return this.getLastDateOfMonth().getDay()};Date.prototype.getFirstDateOfMonth=function(){return new Date(this.getFullYear(),this.getMonth(),1)};Date.prototype.getLastDateOfMonth=function(){return new Date(this.getFullYear(),this.getMonth(),this.getDaysInMonth())};
Date.prototype.getFirstDateOfQuarter=function(){var a=this.getMonth();return new Date(this.getFullYear(),3>a?0:6>a?3:9>a?6:9,1)};Date.prototype.getFirstDateOfHalfYear=function(){return new Date(this.getFullYear(),6>this.getMonth()?0:6,1)};Date.prototype.getFirstDateOfYear=function(){return new Date(this.getFullYear(),0,1)};Date.prototype.getDaysInMonth=function(){var a=this.getMonth();return 1===a&&this.isLeapYear()?29:Date.DaysInMonth[a]};
Date.prototype.set=function(a,b){b==Date.Year?this.setFullYear(a):b==Date.Month?this.setMonth(a):b==Date.Day?this.setDate(a):b==Date.Hour?this.setHours(a):b==Date.Minute?this.setMinutes(a):b==Date.Second?this.setSeconds(a):b==Date.Milli&&this.setMilliseconds(a);return this};
Date.prototype.add=function(a,b){if(!b||0===a)return this;switch(b){case Date.Milli:this.setTime(this.getTime()+a);break;case Date.Second:this.setTime(this.getTime()+1E3*a);break;case Date.Minute:this.setTime(this.getTime()+6E4*a);break;case Date.Hour:this.setTime(this.getTime()+36E5*a);break;case Date.Day:this.setDate(this.getDate()+a);break;case Date.Month:var c=this.getDate(),d=this.getMonth();28<c&&(c=Math.min(c,this.getFirstDateOfMonth().add(a,Date.Month).getLastDateOfMonth().getDate()));this.setDate(c);
this.setMonth(d+a);break;case Date.Year:c=this.getDate(),d=this.getFullYear(),28<c&&(c=Math.min(c,this.getFirstDateOfMonth().add(a,Date.Year).getLastDateOfMonth().getDate())),this.setDate(c),this.setFullYear(d+a)}return this};Date.prototype.addMillisecond=function(a){return this.add(a,Date.Milli)};Date.prototype.addSecond=function(a){return this.add(a,Date.Second)};Date.prototype.addMinute=function(a){return this.add(a,Date.Minute)};Date.prototype.addHour=function(a){return this.add(a,Date.Hour)};
Date.prototype.addDay=function(a){return this.add(a,Date.Day)};Date.prototype.addMonth=function(a){return this.add(a,Date.Month)};Date.prototype.addYear=function(a){return this.add(a,Date.Year)};Date.prototype.truncDay=function(){this.setHours(0);this.setMinutes(0);this.setSeconds(0);this.setMilliseconds(0);return this};Date.prototype.truncMonth=function(){this.setDate(1);this.setHours(0);this.setMinutes(0);this.setSeconds(0);this.setMilliseconds(0);return this};
Date.prototype.toISOString=function(){var a=-this.getTimezoneOffset(),b=this.getFullYear(),c=this.getMonth()+1,d=this.getDate(),e=this.getHours(),f=this.getMinutes(),g=this.getSeconds(),l=this.getMilliseconds(),k="";if(0!=a)var k=Math.floor(a/60),m=a%60,k=(0<=a?"+":"-")+(10>k?"0":"")+k+":"+(10>m?"0":"")+m;return b+"-"+(10>c?"0":"")+c+"-"+(10>d?"0":"")+d+"T"+(10>e?"0":"")+e+":"+(10>f?"0":"")+f+":"+(10>g?"0":"")+g+(0!=l?"."+(100>l?10>l?"00":"0":"")+l:"")+k};JSON.encode=JSON.stringify;JSON.decode=JSON.parse;
var Z8={classes:{},apply:function(a,b){for(var c in b)a[c]=b[c];return a},addMembers:function(a,b){for(var c in b)Z8.addMember(a,b[c],c)},addMember:function(a,b,c){if(void 0!=b){if("function"==typeof b&&null==b.$owner){var d=a[c];null!=d&&(b.$previous=d);b.$owner=a}a[c]=b}},addCallParent:function(a){Z8.addMember(a,function(){return this.callParent.caller.$previous.apply(this,arguments)},"callParent")},newConstructor:function(){return function(){return this.constructor.apply(this,arguments)}},define:function(a,
b){var c=Z8.newConstructor(),d=b.single;delete b.single;var e=b.extend;delete b.extend;var f=b.mixins;delete b.mixins;var g=b.statics;delete b.statics;var l=b.shortClassName;delete b.shortClassName;var k=null;if(null!=e){if(k=Z8.classes[e],null==k)throw'Superclass not found: "'+e+'"';}else k=function(a){return Z8.addMembers(this,a)};e=k.prototype;k=c.prototype=Object.create(e);k.self=k;k.$className=a;c.superclass=k.superclass=e;Z8.addMembers(k,b);Z8.addCallParent(k);Z8.mixin(k,f);Z8.apply(c,g);d||
(Z8.namespace(a,c),Z8.namespace(l,c));return c},mixin:function(a,b){if(null!=b){b=Array.isArray(b)?b:[b];for(var c=0,d=b.length;c<d;c++){var e=Z8.classes[b[c]];if(null==e)throw'Mixin not found: "'+b[c]+'"';var e=e.prototype,f=e.mixinId;if(null==f)throw'Mixed in class must have mixinId: "'+e.$className+'"';for(var g in e)"mixinId"!=g&&void 0===a[g]&&(a[g]=e[g]);null==a.mixins&&(a.mixins={});a.mixins[f]=e}}},namespace:function(a,b){if(null!=a){for(var c=window,d=a.split("."),e=d.length-1,f=d[e],g=0;g<
e;g++){var l=d[g],k=c[l];null==k&&(k=c[l]={});c=k}c[f]=b;return Z8.classes[a]=b}},create:function(a,b){if(String.isString(a)){var c=a;a=Z8.classes[c];if(null==a)throw'Class not found: "'+c+'"';}c=Object.create(a.prototype);a.call(c,b);return c},callback:function(a){if(null!=a){var b,c;"object"==typeof a?(c=a.scope,a=a.fn||a.callback,b=Array.prototype.slice.call(arguments,1)):(c=arguments[1],b=Array.prototype.slice.call(arguments,2));null!=a&&a.apply(c,b)}},isEmpty:function(a){return null==a||""===
a?!0:Array.isArray(a)?0==a.length:!1}};Z8.apply(Event.prototype,{stopEvent:function(){this.stopPropagation();this.preventDefault();this.cancelled=!0},getCharCode:function(){return this.charCode||this.keyCode},getKey:function(){return this.keyCode||this.charCode}});
Z8.apply(Event,{BACKSPACE:8,TAB:9,NUM_CENTER:12,ENTER:13,RETURN:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,CAPS_LOCK:20,ESC:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,PRINT_SCREEN:44,INSERT:45,DELETE:46,ZERO:48,ONE:49,TWO:50,THREE:51,FOUR:52,FIVE:53,SIX:54,SEVEN:55,EIGHT:56,NINE:57,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,Y:89,Z:90,CONTEXT_MENU:93,NUM_ZERO:96,NUM_ONE:97,NUM_TWO:98,NUM_THREE:99,
NUM_FOUR:100,NUM_FIVE:101,NUM_SIX:102,NUM_SEVEN:103,NUM_EIGHT:104,NUM_NINE:105,NUM_MULTIPLY:106,NUM_PLUS:107,NUM_MINUS:109,NUM_PERIOD:110,NUM_DIVISION:111,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123});
Z8.define("Z8.dom.Dom",{shortClassName:"DOM",statics:{emptyTags:{br:!0,frame:!0,hr:!0,img:!0,input:!0,link:!0,meta:!0,col:!0},readyListeners:[],isDom:function(a){return null!=a&&null!=a.addEventListener},get:function(a){return null==a?null:a.isComponent||null!=a.dom?a.dom:DOM.isDom(a)?a:null},isParentOf:function(a,b){if(null==a||null==b)return!1;a=Array.isArray(a)?a.slice(0):[a];for(var c=0,d=0,e=a.length;c<e;c++)null!=(a[c]=DOM.get(a[c]))&&d++;if(0==d)return!1;for(d=document.body;null!=b&&1==b.nodeType&&
b!==d;){c=0;for(e=a.length;c<e;c++)if(b==a[c])return!0;b=b.parentNode}return!1},getCookie:function(a){a=document.cookie.match(a+"=([^;|*]*);*");return null!=a?decodeURIComponent(a[1]||""):""},setCookie:function(a,b,c){document.cookie=a+"="+encodeURIComponent(b)+";expires="+(new Date).addDay(c||2).toUTCString()+";path=/"},selectNode:function(a,b){1==arguments.length&&(b=a,a=document.body);return null==(a=DOM.get(a))?null:a.querySelector(b)},query:function(a,b){1==arguments.length&&(b=a,a=document.body);
return null==(a=DOM.get(a))?null:a.querySelectorAll(b)},markup:function(a){var b="";if(String.isString(a)||Number.isNumber(a))return b+a;if(Array.isArray(a)){for(var c=0,d=a.length;c<d;c++){var e=a[c];null!=e&&(b+=DOM.markup(e))}return b}c=a.tag||"div";b+="<"+c;for(e in a)d=a[e],"tag"!=e&&"children"!=e&&"cn"!=e&&"html"!=e&&"container"!=e&&(b+=" "+("cls"==e?"class":e)+(null!=d?'="'+d+'"':""));null==DOM.emptyTags[c]?(b+=">",null!=(d=a.html)&&(b+=d),null!=(d=a.cn||a.children)&&(b+=DOM.markup(d)),b+=
"</"+c+">"):b+="/>";return b},append:function(a,b){if(null==(a=DOM.get(a||document.body))||null==b)return null;if(DOM.isDom(b))return a.appendChild(b);a.insertAdjacentHTML("beforeend",DOM.markup(b));return a.lastChild},insertBefore:function(a,b){if(null==(a=DOM.get(a))||null==b)return null;if(DOM.isDom(b))return a.insertAdjacentElement("beforebegin",b);a.insertAdjacentHTML("beforebegin",DOM.markup(b));return a.previousSibling},remove:function(a,b){if(null==(a=DOM.get(a)))return null;null!=b?(new Z8.util.DelayedTask).delay(b,
function(a){a.parentElement.removeChild(a)},this,a):a.parentElement.removeChild(a)},getProperty:function(a,b){a=DOM.get(a);return null!=a?a[b]:null},setProperty:function(a,b,c,d){null!=(a=DOM.get(a))&&(null!=d?(new Z8.util.DelayedTask).delay(d,function(a,b,c){a[b]=c},this,a,b,c):a[b]=c)},getStyle:function(a,b){a=DOM.get(a);return null!=a?a.style[b]:null},setStyle:function(a,b,c,d){null!=c&&null!=(a=DOM.get(a))&&(null!=d?(new Z8.util.DelayedTask).delay(d,function(a,b,c){a.style[b]=c},this,a,b,c):a.style[b]=
c)},getParent:function(a){return DOM.getProperty(a,"parentNode")},getComputedStyle:function(a){a=DOM.get(a);return null!=a?window.getComputedStyle(a):null},getClipping:function(a){if(null==(a=DOM.get(a)))return null;var b=document.body;for(a=a.parentNode;null!=a&&1==a.nodeType;){if(a==b)return b;var c=window.getComputedStyle(a).overflowY;if("hidden"==c||"auto"==c)return a;a=a.parentNode}return null},getAttribute:function(a,b){a=DOM.get(a);return null!=a?a.getAttribute(b):null},getIntAttribute:function(a,
b){var c=DOM.getAttribute(a,b);return null!=c?Parser.integer(c):null},setAttribute:function(a,b,c){null!=(a=DOM.get(a))&&a.setAttribute(b,c)},focus:function(a,b){if(null==(a=DOM.get(a))||null==a.focus)return!1;a.focus();b&&null!=a.select&&a.select();return!0},scroll:function(a,b,c){null!=(a=DOM.get(a))&&null!=a.focus&&(a.scrollLeft=b,a.scrollTop=c)},parseCls:function(a){return(String.isString(a)?a.toLowerCase().split(" "):a)||[]},getCls:function(a){DOM.getProperty(a,"className")},setCls:function(a,
b,c){DOM.setProperty(a,"className",Array.isArray(b)?b.join(" "):b,c)},removeCls:function(a,b,c){null!=(a=DOM.get(a))&&(c=DOM.parseCls(a.className),b=c.indexOf(b),-1!=b&&(c.splice(b,1),DOM.setCls(a,c)))},addCls:function(a,b,c){if(null!=(a=DOM.get(a))){var d=DOM.parseCls(a.className);-1==d.indexOf(b)&&(d.push(b),DOM.setCls(a,d,c))}},swapCls:function(a,b,c,d,e){if(null!=(a=DOM.get(a))){var f=DOM.parseCls(a.className),g=b?c:d;c=b?d:c;null!=g&&(-1==f.indexOf(g)?f.push(g):g=null);null!=c&&(b=f.indexOf(c),
-1!=b?f.splice(b,1):c=null);null==g&&null==c||DOM.setCls(a,f,e);return f}},getValue:function(a){if(null==(a=DOM.get(a)))return null;var b=a.tagName;return"INPUT"==b||"TEXTAREA"==b?"checkbox"==a.type?a.checked:a.value:a.textContent},setValue:function(a,b,c){if(null!=(a=DOM.get(a))){var d=a.tagName;DOM.setProperty(a,"INPUT"==d||"TEXTAREA"==d?"checkbox"==a.type?"checked":"value":"textContent",b||"",c)}},setTitle:function(a,b,c){DOM.setProperty(a,"title",b,c)},setInnerHTML:function(a,b,c){DOM.setProperty(a,
"innerHTML",b,c)},setReadOnly:function(a,b,c){DOM.setProperty(a,"readOnly",b,c)},setDisabled:function(a,b,c){DOM.setProperty(a,"disabled",b,c)},setTabIndex:function(a,b,c){DOM.setProperty(a,"tabIndex",b,c)},setDisplay:function(a,b,c){DOM.setStyle(a,"display",b,c)},setHidden:function(a,b,c){DOM.setStyle(a,"visibility",b?"hidden":"visible",c)},getOffsetTop:function(a){return Ems.pixelsToEms(DOM.getProperty(a,"offsetTop"))},getOffsetLeft:function(a){return Ems.pixelsToEms(DOM.getProperty(a,"offsetLeft"))},
getOffsetWidth:function(a){return Ems.pixelsToEms(DOM.getProperty(a,"offsetWidth"))},getOffsetHeight:function(a){return Ems.pixelsToEms(DOM.getProperty(a,"offsetHeight"))},getClientWidth:function(a){return Ems.pixelsToEms(DOM.getProperty(a,"clientWidth"))},getClientHeight:function(a){return Ems.pixelsToEms(DOM.getProperty(a,"clientHeight"))},getPoint:function(a,b){b=DOM.getStyle(a,b);return null!=b?parseFloat(b):null},setPoint:function(a,b,c,d){null!=c&&DOM.setStyle(a,b,String.isString(c)?c:c+"em",
d)},getLeft:function(a){return DOM.getPoint(a,"left")},setLeft:function(a,b,c){DOM.setPoint(a,"left",b,c)},getRight:function(a){return DOM.getPoint(a,"right")},setRight:function(a,b,c){DOM.setPoint(a,"right",b,c)},getTop:function(a){return DOM.getPoint(a,"top")},setTop:function(a,b,c){DOM.setPoint(a,"top",b,c)},getBottom:function(a){return DOM.getPoint(a,"bottom")},setBottom:function(a,b,c){DOM.setPoint(a,"bottom",b,c)},getWidth:function(a){return DOM.getPoint(a,"width")},setWidth:function(a,b,c){DOM.setPoint(a,
"width",b,c)},getHeight:function(a){return DOM.getPoint(a,"height")},setHeight:function(a,b,c){DOM.setPoint(a,"height",b,c)},setCssText:function(a,b,c){DOM.setStyle(a,"cssText",b,c)},rotate:function(a,b){if(null!=a){var c="fa-rotate-"+b;0!=b?(DOM.addCls(a,"fa-transform-transition"),DOM.addCls(a,c),a.rotationCls=c):(DOM.removeCls(a,a.rotationCls),delete a.rotationCls)}},substitutes:{click:"touchend",mousedown:"touchstart"},on:function(a,b,c,d,e){if(null!=(a=DOM.get(a))){b=b.toLowerCase();var f=a.eventsData;
null==f&&(f=a.eventsData=f={});var g=f[b]||[],l=function(a){var b=a.currentTarget.eventsData;if(null!=b&&(b=b[a.type],null!=b))for(var b=[].concat(b),c=0,d=b.length;c<d&&(Z8.callback(b[c],a,a.target),!a.cancelled);c++);};if(null==c)throw"DOM.on: fn is null";g.push({fn:c,scope:d,callback:l,capture:e});f[b]=g;1==g.length&&a.addEventListener(b,l,e)}},un:function(a,b,c,d){if(null!=(a=DOM.get(a))){b=b.toLowerCase();var e=a.eventsData;if(null!=e){var f=e[b];if(null!=f){for(var g=0,l=f.length;g<l;g++){var k=
f[g];if(k.fn==c&&k.scope==d){f.removeAt(g);0==f.length&&(a.removeEventListener(b,k.callback,k.capture),delete e[b]);break}}0==Object.keys(e).length&&delete a.eventsData}}}},download:function(a,b,c){var d=DOM.append(document.body,{tag:"iframe",html:'<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>',src:"",hidden:!0});d.src=encodeURI(a.replace(/\\/g,"/"))+"?&session="+Application.session+(null!=b?"&serverId="+b:"");(new Z8.util.DelayedTask).delay(500,DOM.downloadCallback,
this,a,d,c)},downloadCallback:function(a,b,c){var d=b.contentDocument;if("complete"==d.readyState){var d=d.body.innerHTML,e=Z8.isEmpty(d);e||(d="{"==d.charAt(0)?JSON.decode(d):{info:{messages:[{text:"'"+a+"' - \u0444\u0430\u0439\u043b \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d",type:"error"}]}},Application.message(d.info.messages));Z8.callback(c,e);DOM.remove(b,1E4)}else(new Z8.util.DelayedTask).delay(500,DOM.downloadCallback,this,a,b,c)},onReady:function(a,b){DOM.readyListeners.push({fn:a,
scope:b})},onContextMenu:function(a,b){"INPUT"!=b.tagName&&"PRE"!=b.tagName&&a.stopEvent()},onReadyEvent:function(a,b){for(var c=DOM.readyListeners,d=0,e=c.length;d<e;d++)Z8.callback(c[d]);delete DOM.readyListeners;DOM.un(window,"load",DOM.onReadyEvent);if(null!=DOM.onContextMenu)DOM.on(window,"contextmenu",DOM.onContextMenu);-1!=window.navigator.userAgent.toLowerCase().indexOf("gecko/")&&DOM.addCls(document.body,"gecko")}}});DOM.on(window,"load",DOM.onReadyEvent);
Z8.define("Z8.util.Ems",{shortClassName:"Ems",statics:{Base:parseFloat(DOM.getComputedStyle(document.body).fontSize),UnitHeight:4,UnitSpacing:.71428571,unitsToEms:function(a){return a?a*Ems.UnitHeight+(a-1)*Ems.UnitSpacing:0},pixelsToEms:function(a){return a?(a/Ems.Base).round(8):0},emsToPixels:function(a){return Math.ceil(a*Ems.Base)}}});
Z8.define("Z8.Rect",{shortClassName:"Rect",left:0,top:0,right:0,bottom:0,constructor:function(a,b,c,d){Number.isNumber(a)?(this.left=Math.min(a,c),this.top=Math.min(b,d),this.right=Math.max(a,c),this.bottom=Math.max(b,d)):null!=a&&(b=DOM.get(a),null!=b?(a=b.getBoundingClientRect(),this.left=Ems.pixelsToEms(a.left),this.top=Ems.pixelsToEms(a.top),this.right=Ems.pixelsToEms(a.right),this.bottom=Ems.pixelsToEms(a.bottom)):(this.left=a.left,this.top=a.top,this.right=a.right,this.bottom=a.bottom));this.width=
this.right-this.left;this.height=this.bottom-this.top},offset:function(a,b){this.left+=a;this.right+=a;this.top+=b||0;this.bottom+=b||0;return this}});Z8.define("guid",{statics:{Null:"00000000-0000-0000-0000-000000000000"}});Z8.define("Z8.server.type",{shortClassName:"Type",statics:{Guid:"guid",Integer:"int",Float:"float",Boolean:"boolean",Date:"date",Datetime:"datetime",Datespan:"datespan",String:"string",Binary:"binary",Text:"text",File:"file",Files:"attachments",Json:"json"}});
Z8.define("Z8.RecordLock",{shortClassName:"RecordLock",statics:{None:0,Full:1,Edit:2,Destroy:3}});
Z8.define("Z8.Operation",{shortClassName:"Operation",statics:{Eq:"eq",NotEq:"notEq",Contains:"contains",NotContains:"notContains",BeginsWith:"beginsWith",NotBeginsWith:"notBeginsWith",EndsWith:"endsWith",NotEndsWith:"notEndsWith",IsEmpty:"isEmpty",IsNotEmpty:"isNotEmpty",GT:"gt",GE:"ge",LT:"lt",LE:"le",Today:"today",Tomorrow:"tomorrow",Yesterday:"yesterday",LastWeek:"lastWeek",ThisWeek:"thisWeek",NextWeek:"nextWeek",LastMonth:"lastMonth",ThisMonth:"thisMonth",NextMonth:"nextMonth",LastYear:"lastYear",
ThisYear:"thisYear",NextYear:"nextYear",LastDays:"lastDays",NextDays:"nextDays",LastHours:"lastHours",NextHours:"nextHours",isTrue:"isTrue",isFalse:"isFalse"}});
Z8.define("Z8.util.Format",{shortClassName:"Format",statics:{Date:"d.m.Y",ShortDate:"d.m.y",LongDate:"j F Y",Time:"H:i",LongTime:"H:i:s",Datetime:"d.m.Y H:i",LongDatetime:"j F Y H:i",Integer:"0,000",Float:"0,000.00",TrueText:"\u0434\u0430",FalseText:"\u043d\u0435\u0442",ThousandSeparator:" ",DecimalSeparator:",",charWidth:null,measures:{},list:function(){for(var a="",b=0,c=arguments.length;b<c;b++){var d=arguments[b];Z8.isEmpty(d)||(a+=(""==a?"":", ")+d)}return a},placeholder:function(a,b){return Z8.isEmpty(a)?
b:a},nl2br:function(a){var b=null;if(Array.isArray(a)){for(var b=[],c=0;c<a.length;c++){var d=a[c];b.push((d.text||d).replace(/\n/g,"<br>"))}b=b.join("<br>")}else null!=a&&(b=(a.text||a).replace(/\n/g,"<br>"));return b},toHtmlString:function(a){return Format.nl2br(a.text||a).replace(/ /g,string.Empty)},htmlEncode:function(a){return null!=a&&String.isString(a)?a.replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/'/g,"&#39;").replace(/</g,"&lt;").replace(/>/g,"&gt;"):null},htmlDecode:function(a){return null==
a?null:a.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&")},integer:function(a,b){return Format.number(a,null!=b?b:Format.Integer)},"float":function(a,b){return Format.number(a,null!=b?b:Format.Float)},percent:function(a,b){a=Format.number(a,null!=b?b:Format.Integer);return null!=a?a+"%":a},date:function(a,b){return Format.formatDate(a,null!=b?b:Format.Date)},datetime:function(a,b){return Format.formatDate(a,null!=b?b:Format.Datetime)},dateOrTime:function(a,
b,c){if(null==a||""==a)return"";b=b||Format.Datetime;c=c||Format.Time;var d=new Date,e=(new Date).add(-1,Date.Day),d=Date.isEqualDate(a,d),e=Date.isEqualDate(a,e);return d?"\u0441\u0435\u0433\u043e\u0434\u043d\u044f "+Format.date(a,c):e?"\u0432\u0447\u0435\u0440\u0430 "+Format.date(a,c):Format.date(a,b)},fileSize:function(a){if(1024>a)return a=Format.integer(a,"0,0"),""!=a?a+" B":"";if(1048576>a)return a=Format["float"](a/1024,"0,0.##"),""!=a?a+" KB":"";if(1073741824>a)return a=Format["float"](a/
1048576,"0,0.##"),""!=a?a+" MB":"";a=Format["float"](a/1073741824,"0,0.##");return""!=a?a+" GB":""},getCharWidth:function(){if(null==Format.charWidth){var a=DOM.append(document.body,{html:"abcdefghABCDEFGH1234567890",style:"position: fixed; top: -10000;"});Format.charWidth=(new Rect(a)).width/26;DOM.remove(a)}return Format.charWidth},measureDate:function(a){var b=Format.measures[a];if(null!=b)return b;b=Format.date(new Date(2E3,8,20,22,22,22,222),a).length*Format.getCharWidth();return Format.measures[a]=
b},number:function(a,b){if(null==b)return a;if(isNaN(a))return"";var c=Format.formats[b];if(null==c){var c=0,d="",e=-1!==b.indexOf(","),f=b.replace(/[^\d\.#]/g,"").split("."),g=b.replace(/[\d,\.#]+/,"");if(2<f.length)throw"Invalid number format, should have no more than 1 decimal";if(2==f.length){var c=f[1].length,l=f[1].match(/#+$/);l&&(d='trailingZeroes=new RegExp(Format.DecimalSeparator.replace(/([-.*+?\\^${}()|\\[\\]\\/\\\\])/g, "\\\\$1") + "*0{0,'+l[0].length+'}$")')}d=["var neg,absVal,fnum,parts"+
(e?",thousandSeparator,thousands=[],j,n,i":"")+(g?',format="'+b+'"':"")+',trailingZeroes;return function(v){if(typeof v!=="number"&&isNaN(v=parseFloat(v)))return"";neg=v<0;',"absVal=Math.abs(v);","fnum=absVal.toFixed("+c+");",d,";"];e?(c&&(d[d.length]='parts=fnum.split(".");',d[d.length]="fnum=parts[0];"),d[d.length]="if(absVal>=1000) {",d[d.length]="thousandSeparator=Format.ThousandSeparator;thousands.length=0;j=fnum.length;n=fnum.length%3||3;for(i=0;i<j;i+=n){if(i!==0){n=3;}thousands[thousands.length]=fnum.substr(i,n);}fnum=thousands.join(thousandSeparator);}",
c&&(d[d.length]="fnum += Format.DecimalSeparator+parts[1];")):c&&(d[d.length]='if(Format.DecimalSeparator!=="."){parts=fnum.split(".");fnum=parts[0]+Format.DecimalSeparator+parts[1];}');d[d.length]='if(neg&&fnum!=="'+(c?"0."+String.repeat("0",c):"0")+'") { fnum="-"+fnum; }';l&&(d[d.length]='fnum=fnum.replace(trailingZeroes,"");');d[d.length]="return ";d[d.length]=g?"format.replace(/[\\d,\\.#]+/, fnum);":"fnum;";d[d.length]="};";c=Format.formats[b]=Function.prototype.constructor.call(Function.prototype,
d.join(""))()}return c(a)},formatDate:function(a,b){var c=Format.formats;if(!Date.isDate(a))return"";null==c[b]&&Format.createFormat(b);return c[b].call(a)},formats:{},formatCodes:{Y:'String.padLeft(this.getFullYear(), 4, "0")',y:'("" + this.getFullYear()).substring(2, 4)',F:"this.getMonthName()",M:"this.getShortMonthName()",m:'String.padLeft(this.getMonth() + 1, 2, "0")',n:"(this.getMonth() + 1)",t:"this.getDaysInMonth()",W:'String.padLeft(this.getWeekOfYear(), 2, "0")',w:"this.getWeekOfYear()",
z:"this.getDayOfYear()",N:"this.getDayOfWeek() + 1",l:"this.getDayName()",D:"this.getShortDayName()",d:'String.padLeft(this.getDate(), 2, "0")',j:"this.getDate()",g:"((this.getHours() % 12) ? this.getHours() % 12 : 12)",G:"this.getHours()",h:'String.padLeft((this.getHours() % 12) ? this.getHours() % 12 : 12, 2, "0")',H:'String.padLeft(this.getHours(), 2, "0")',L:"(this.isLeapYear() ? 1 : 0)",o:"(this.getFullYear() + (this.getWeekOfYear() == 1 && this.getMonth() > 0 ? 1 : (this.getWeekOfYear() >= 52 && this.getMonth() < 11 ? -1 : 0)))",
a:'(this.getHours() < 12 ? "am" : "pm")',A:'(this.getHours() < 12 ? "AM" : "PM")',i:'String.padLeft(this.getMinutes(), 2, "0")',s:'String.padLeft(this.getSeconds(), 2, "0")',S:'String.padLeft(this.getMilliseconds(), 3, "0")',O:'((this.getTimezoneOffset() > 0 ? "-" : "+") + String.padLeft(Math.floor(Math.abs(this.getTimezoneOffset()) / 60), 2, "0") + String.PadLeft(Math.abs(this.getTimezoneOffset() % 60), 2, "0"))',P:'((this.getTimezoneOffset() > 0 ? "-" : "+") + String.padLeft(Math.floor(Math.abs(this.getTimezoneOffset()) / 60), 2, "0") + ":" + String.PadLeft(Math.abs(this.getTimezoneOffset() % 60), 2, "0"))',
T:'this.toString().replace(/^.* (?:((.*))|([A-Z]{1,5})(?:[-+][0-9]{4})?(?: -?d+)?)$/, "$1$2").replace(/[^A-Z]/g, "")',Z:"(this.getTimezoneOffset() * -60)",c:function(){for(var a=[],b=0;12>b;b++){var c="Y-m-dTH:i:sP".charAt(b);a.push("T"===c?"'T'":Format.getFormatCode(c))}return a.join(" + ")},C:function(){return"this.toISOString()"},U:"Math.round(this.getTime() / 1000)"},createFormat:function(a){for(var b=[],c=!1,d,e=0,f=a.length;e<f;e++)d=a.charAt(e),c||"\\"!==d?c?(c=!1,b.push("'"+Format.escape(d)+
"'")):b.push("\n"==d?"'\\n'":Format.getFormatCode(d)):c=!0;b="return "+b.join("+");Format.formats[a]=Function.prototype.constructor.call(Function.prototype,b)},escape:function(a){return a.replace(/('|\\)/g,"\\$1")},getFormatCode:function(a){var b=Format.formatCodes[a];null!=b&&(b="function"==typeof b?b():b,Format.formatCodes[a]=b);return b||"'"+Format.escape(a)+"'"}}});
Z8.define("Z8.util.Parser",{shortClassName:"Parser",statics:{datetime:function(a,b){if(Z8.isEmpty(a))return null;String.isString(a)&&(a=a.replace(/^(\d\d?)([\.\-//])(\d\d?)([\.\-//])/,"$3$2$1$4"));a=new Date(a);return isNaN(a)?null:a},date:function(a,b){return Z8.util.Parser.datetime(a,b)},integer:function(a,b){if(Number.isNumber(a))return a.round();a=parseInt(a.replace(/\s/g,""),b);return isNaN(a)?null:a},"float":function(a){if(Number.isNumber(a))return a;a=parseFloat(a.replace(/,/g,".").replace(/\s/g,
""));return isNaN(a)?null:a},"boolean":function(a){return String.isString(a)?"true"===a:a}}});
Z8.define("Z8.util.MD5",{shortClassName:"MD5",statics:{hexcase:0,b64pad:"",hex:function(a){return MD5.rstr2hex(MD5.rstr(MD5.str2rstr_utf8(a)))},b64:function(a){return MD5.rstr2b64(MD5.rstr(MD5.str2rstr_utf8(a)))},any:function(a,b){return MD5.rstr2any(MD5.rstr(MD5.str2rstr_utf8(a)),b)},hex_hmac:function(a,b){return MD5.rstr2hex(MD5.rstr_hmac(MD5.str2rstr_utf8(a),MD5.str2rstr_utf8(b)))},b64_hmac:function(a,b){return MD5.rstr2b64(MD5.rstr_hmac(MD5.str2rstr_utf8(a),MD5.str2rstr_utf8(b)))},any_hmac:function(a,
b,c){return MD5.rstr2any(MD5.rstr_hmac(MD5.str2rstr_utf8(a),MD5.str2rstr_utf8(b)),c)},vm_test:function(){return"900150983cd24fb0d6963f7d28e17f72"==MD5.hex("abc").toLowerCase()},rstr:function(a){return MD5.binl2rstr(MD5.binl(MD5.rstr2binl(a),8*a.length))},rstr_hmac:function(a,b){var c=MD5.rstr2binl(a);16<c.length&&(c=MD5.binl(c,8*a.length));for(var d=Array(16),e=Array(16),f=0;16>f;f++)d[f]=c[f]^909522486,e[f]=c[f]^1549556828;c=MD5.binl(d.concat(MD5.rstr2binl(b)),512+8*b.length);return MD5.binl2rstr(MD5.binl(e.concat(c),
640))},rstr2hex:function(a){for(var b=MD5.hexcase?"0123456789ABCDEF":"0123456789abcdef",c="",d=0;d<a.length;d++)var e=a.charCodeAt(d),c=c+(b.charAt(e>>>4&15)+b.charAt(e&15));return c},rstr2b64:function(a){for(var b="",c=a.length,d=0;d<c;d+=3)for(var e=a.charCodeAt(d)<<16|(d+1<c?a.charCodeAt(d+1)<<8:0)|(d+2<c?a.charCodeAt(d+2):0),f=0;4>f;f++)b=8*d+6*f>8*a.length?b+b64pad:b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(e>>>6*(3-f)&63);return b},rstr2any:function(a,b){var c=
b.length,d,e,f,g,l,k=Array(Math.ceil(a.length/2));for(d=0;d<k.length;d++)k[d]=a.charCodeAt(2*d)<<8|a.charCodeAt(2*d+1);var m=Math.ceil(8*a.length/(Math.log(b.length)/Math.log(2))),n=Array(m);for(e=0;e<m;e++){l=[];for(d=g=0;d<k.length;d++)if(g=(g<<16)+k[d],f=Math.floor(g/c),g-=f*c,0<l.length||0<f)l[l.length]=f;n[e]=g;k=l}c="";for(d=n.length-1;0<=d;d--)c+=b.charAt(n[d]);return c},str2rstr_utf8:function(a){for(var b="",c=-1,d,e;++c<a.length;)d=a.charCodeAt(c),e=c+1<a.length?a.charCodeAt(c+1):0,55296<=
d&&56319>=d&&56320<=e&&57343>=e&&(d=65536+((d&1023)<<10)+(e&1023),c++),127>=d?b+=String.fromCharCode(d):2047>=d?b+=String.fromCharCode(192|d>>>6&31,128|d&63):65535>=d?b+=String.fromCharCode(224|d>>>12&15,128|d>>>6&63,128|d&63):2097151>=d&&(b+=String.fromCharCode(240|d>>>18&7,128|d>>>12&63,128|d>>>6&63,128|d&63));return b},str2rstr_utf16le:function(a){for(var b="",c=0;c<a.length;c++)b+=String.fromCharCode(a.charCodeAt(c)&255,a.charCodeAt(c)>>>8&255);return b},str2rstr_utf16be:function(a){for(var b=
"",c=0;c<a.length;c++)b+=String.fromCharCode(a.charCodeAt(c)>>>8&255,a.charCodeAt(c)&255);return b},rstr2binl:function(a){for(var b=Array(a.length>>2),c=0;c<b.length;c++)b[c]=0;for(c=0;c<8*a.length;c+=8)b[c>>5]|=(a.charCodeAt(c/8)&255)<<c%32;return b},binl2rstr:function(a){for(var b="",c=0;c<32*a.length;c+=8)b+=String.fromCharCode(a[c>>5]>>>c%32&255);return b},binl:function(a,b){a[b>>5]|=128<<b%32;a[(b+64>>>9<<4)+14]=b;for(var c=1732584193,d=-271733879,e=-1732584194,f=271733878,g=MD5.md5_ff,l=MD5.md5_gg,
k=MD5.md5_hh,m=MD5.md5_ii,n=MD5.safe_add,h=0;h<a.length;h+=16)var p=c,q=d,r=e,t=f,c=g(c,d,e,f,a[h+0],7,-680876936),f=g(f,c,d,e,a[h+1],12,-389564586),e=g(e,f,c,d,a[h+2],17,606105819),d=g(d,e,f,c,a[h+3],22,-1044525330),c=g(c,d,e,f,a[h+4],7,-176418897),f=g(f,c,d,e,a[h+5],12,1200080426),e=g(e,f,c,d,a[h+6],17,-1473231341),d=g(d,e,f,c,a[h+7],22,-45705983),c=g(c,d,e,f,a[h+8],7,1770035416),f=g(f,c,d,e,a[h+9],12,-1958414417),e=g(e,f,c,d,a[h+10],17,-42063),d=g(d,e,f,c,a[h+11],22,-1990404162),c=g(c,d,e,f,a[h+
12],7,1804603682),f=g(f,c,d,e,a[h+13],12,-40341101),e=g(e,f,c,d,a[h+14],17,-1502002290),d=g(d,e,f,c,a[h+15],22,1236535329),c=l(c,d,e,f,a[h+1],5,-165796510),f=l(f,c,d,e,a[h+6],9,-1069501632),e=l(e,f,c,d,a[h+11],14,643717713),d=l(d,e,f,c,a[h+0],20,-373897302),c=l(c,d,e,f,a[h+5],5,-701558691),f=l(f,c,d,e,a[h+10],9,38016083),e=l(e,f,c,d,a[h+15],14,-660478335),d=l(d,e,f,c,a[h+4],20,-405537848),c=l(c,d,e,f,a[h+9],5,568446438),f=l(f,c,d,e,a[h+14],9,-1019803690),e=l(e,f,c,d,a[h+3],14,-187363961),d=l(d,e,
f,c,a[h+8],20,1163531501),c=l(c,d,e,f,a[h+13],5,-1444681467),f=l(f,c,d,e,a[h+2],9,-51403784),e=l(e,f,c,d,a[h+7],14,1735328473),d=l(d,e,f,c,a[h+12],20,-1926607734),c=k(c,d,e,f,a[h+5],4,-378558),f=k(f,c,d,e,a[h+8],11,-2022574463),e=k(e,f,c,d,a[h+11],16,1839030562),d=k(d,e,f,c,a[h+14],23,-35309556),c=k(c,d,e,f,a[h+1],4,-1530992060),f=k(f,c,d,e,a[h+4],11,1272893353),e=k(e,f,c,d,a[h+7],16,-155497632),d=k(d,e,f,c,a[h+10],23,-1094730640),c=k(c,d,e,f,a[h+13],4,681279174),f=k(f,c,d,e,a[h+0],11,-358537222),
e=k(e,f,c,d,a[h+3],16,-722521979),d=k(d,e,f,c,a[h+6],23,76029189),c=k(c,d,e,f,a[h+9],4,-640364487),f=k(f,c,d,e,a[h+12],11,-421815835),e=k(e,f,c,d,a[h+15],16,530742520),d=k(d,e,f,c,a[h+2],23,-995338651),c=m(c,d,e,f,a[h+0],6,-198630844),f=m(f,c,d,e,a[h+7],10,1126891415),e=m(e,f,c,d,a[h+14],15,-1416354905),d=m(d,e,f,c,a[h+5],21,-57434055),c=m(c,d,e,f,a[h+12],6,1700485571),f=m(f,c,d,e,a[h+3],10,-1894986606),e=m(e,f,c,d,a[h+10],15,-1051523),d=m(d,e,f,c,a[h+1],21,-2054922799),c=m(c,d,e,f,a[h+8],6,1873313359),
f=m(f,c,d,e,a[h+15],10,-30611744),e=m(e,f,c,d,a[h+6],15,-1560198380),d=m(d,e,f,c,a[h+13],21,1309151649),c=m(c,d,e,f,a[h+4],6,-145523070),f=m(f,c,d,e,a[h+11],10,-1120210379),e=m(e,f,c,d,a[h+2],15,718787259),d=m(d,e,f,c,a[h+9],21,-343485551),c=n(c,p),d=n(d,q),e=n(e,r),f=n(f,t);return[c,d,e,f]},md5_cmn:function(a,b,c,d,e,f){var g=MD5.safe_add;return g(MD5.bit_rol(g(g(b,a),g(d,f)),e),c)},md5_ff:function(a,b,c,d,e,f,g){return MD5.md5_cmn(b&c|~b&d,a,b,e,f,g)},md5_gg:function(a,b,c,d,e,f,g){return MD5.md5_cmn(b&
d|c&~d,a,b,e,f,g)},md5_hh:function(a,b,c,d,e,f,g){return MD5.md5_cmn(b^c^d,a,b,e,f,g)},md5_ii:function(a,b,c,d,e,f,g){return MD5.md5_cmn(c^(b|~d),a,b,e,f,g)},safe_add:function(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535},bit_rol:function(a,b){return a<<b|a>>>32-b}}});
Z8.define("Z8.util.DelayedTask",{delay:function(a,b,c){this.cancel();this.fn=b;this.scope=c;this.params=Array.prototype.slice.call(arguments,3);0==a?(this.interval=0,this.timerFn(this)):this.interval=setInterval(this.timerFn,a,this)},cancel:function(){null!=this.interval&&(clearInterval(this.interval),this.interval=null)},timerFn:function(a){null!=a.interval&&(a.cancel(),a.fn.apply(a.scope,a.params))}});
Z8.define("Z8.Object",{dispose:function(){this.listeners=null;this.disposed=!0},on:function(a,b,c){var d=this.listeners=this.listeners||{};a=a.toLowerCase();var e=d[a]||[];e.push({fn:b,scope:c});d[a]=e},un:function(a,b,c){a=a.toLowerCase();b=this.listeners;if(null!=b&&null!=(b=b[a])){a=0;for(var d=b.length;a<d;a++)if(b[a].scope==c){b.removeAt(a);break}}},fireEvent:function(a){var b=this.listeners;if(null!=b&&null!=(b=b[a.toLowerCase()]))for(var b=[].concat(b),c=Array.prototype.slice.call(arguments,
1),d=0,e=b.length;d<e;d++){var f=b[d];null!=f.fn&&f.fn.apply(f.scope,c)}}});
